optimizeLabelClassification: optimizeLabelClassification.cpp 
	g++ optimizeLabelClassification.cpp -lgsl -lgslcblas -o  optimizeLabelClassification

optimizeLabelClassification_pruning: optimizeLabelClassification_pruning.cpp 
	g++ optimizeLabelClassification_pruning.cpp -lgsl -lgslcblas -o  optimizeLabelClassification_pruning
